feat: add api tests for the new controllers
SciCatProject/scicat-backend-next pull request #1580
Opened 2024-12-20 07:21 UTC by martin-trajanovski

## Description
This is PR that adds unit and api tests for the dataset v4 controllers.

## Motivation
After adding the new controllers we need to test all this refactor and also the public endpoints and access to the data.

## Fixes

* https://jira.ess.eu/browse/SWAP-4366

## Changes:

* adding tests for dataset v4 controllers

## Tests included

- [x] Included for each change/fix?
- [x] Passing? 

## Documentation
- [x] swagger documentation updated (required for API changes)
- [ ] official documentation updated

### official documentation info

2025-01-13 07:43 UTC, martin-trajanovski commented
@nitrosx or @Junjiequan maybe this one should be reviewed and merged before the https://github.com/SciCatProject/scicat-backend-next/pull/154 as it pushes changes into that branch first.

2025-01-13 13:21 UTC, nitrosx requested changes

2025-01-13 13:21 UTC, nitrosx commented on src/datasets/datasets.v4.controller.ts
> +
Can you explain why this explicit conversion is needed?

2025-01-13 13:21 UTC, nitrosx commented on test/DatasetV4.js
> +    it("0205: should fetch all dataset relation fields if provided in the filter", async () => {
Should change `should fetch all dataset relation fields if provided in the filter` to `should fetch all datasets with related items when requested with all relations"

2025-01-13 13:21 UTC, nitrosx commented on test/DatasetV4.js
> +  describe("Datasets v4 update tests", () => {
There is already another section with `Datasets v4 update tests`. Why two?

2025-01-13 13:21 UTC, nitrosx commented on test/DatasetV4.js
> +  describe("Datasets v4 update tests", () => {
Change to `Delete`. :)

2025-01-13 13:21 UTC, nitrosx commented on test/DatasetV4Access.js
AS first version it looks good.

2025-01-13 14:53 UTC, martin-trajanovski commented on src/datasets/datasets.v4.controller.ts
> +
I think the main usage of this endpoint is to check if the input you provide is a valid dataset and return true/false based on that. If we put the `CreateDatasetDto` as a type for the input parameter the endpoint returns 400 (Bad request) all the time until we provide a valid input. And then once we provide a valid input it will always return `true` as a value. So my point is that in the previous case this endpoint will never return `false` as a value because of the input parameter validation. I think it makes more sense to accept any input as `object` in this endpoint and validate it inside as we are already doing and then return `true/false` based on the result. @nitrosx please let me know if this explains my change and if it is a reasonable one.

2025-01-14 08:43 UTC, nitrosx approved these changes

2025-01-14 08:48 UTC, nitrosx commented on src/datasets/datasets.v4.controller.ts
> +
@martin-trajanovski cristal clear!!!

2025-01-14 08:50 UTC, merged